# Generated by Django 3.1.3 on 2021-01-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('bag_NR', models.IntegerField(primary_key=True, serialize=False)),
                ('bag_type', models.CharField(choices=[('PREBAG', 'Voorloopzakje'), ('MEDICATIONBAG', 'Medicatiezakje'), ('AFTERBAG', 'Naloopzakje')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_NR', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('machine_ID', models.CharField(max_length=10)),
                ('packaging_code', models.IntegerField()),
                ('run_day', models.CharField(choices=[('MONDAY', 'Maandag'), ('TUESDAY', 'Dinsdag'), ('WEDNESDAY', 'Woensdag'), ('THURSDAY', 'Donderdag'), ('FRIDAY', 'Vrijdag'), ('SATURDAY', 'Zaterdag'), ('SUNDAY', 'Zondag')], max_length=10)),
                ('DB', models.CharField(max_length=40)),
                ('week', models.IntegerField()),
                ('leave_day', models.CharField(choices=[('MONDAY', 'Maandag'), ('TUESDAY', 'Dinsdag'), ('WEDNESDAY', 'Woensdag'), ('THURSDAY', 'Donderdag'), ('FRIDAY', 'Vrijdag'), ('SATURDAY', 'Zaterdag'), ('SUNDAY', 'Zondag')], max_length=10)),
                ('leave_time', models.TimeField()),
                ('forward_day', models.CharField(choices=[('MONDAY', 'Maandag'), ('TUESDAY', 'Dinsdag'), ('WEDNESDAY', 'Woensdag'), ('THURSDAY', 'Donderdag'), ('FRIDAY', 'Vrijdag'), ('SATURDAY', 'Zaterdag'), ('SUNDAY', 'Zondag')], max_length=10)),
                ('forward_time', models.TimeField()),
                ('remarks_end_control', models.CharField(max_length=200)),
                ('checked_by', models.CharField(max_length=40)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('inspector', models.CharField(max_length=40)),
                ('batch_started', models.DateTimeField()),
                ('total_NR_bags', models.IntegerField()),
                ('bags_checked', models.IntegerField()),
                ('total_NR_patients', models.IntegerField()),
                ('bags_rejected', models.IntegerField()),
                ('NR_to_double_check', models.IntegerField()),
                ('double_checked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_NR', models.IntegerField()),
                ('institute', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PillsToBeAdded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pil_ID', models.IntegerField()),
                ('medication_name', models.CharField(max_length=40)),
                ('free_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('roll_NR', models.IntegerField(primary_key=True, serialize=False)),
                ('patient', models.CharField(max_length=40)),
                ('batch_NR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.batch')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_NR', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='API.batch')),
                ('order_NR', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='API.order')),
            ],
        ),
        migrations.CreateModel(
            name='MissingPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=40)),
                ('corrected_by', models.CharField(max_length=40)),
                ('checked_by', models.CharField(max_length=40)),
                ('bag_NR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.bag')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_NR', models.IntegerField()),
                ('error', models.CharField(choices=[('TOO_MUCH', 'Te veel'), ('TOO_LITTLE', 'Te weinig'), ('TOO_EARLY', 'Te vroeg'), ('TOO_LATE', 'Te laat')], max_length=10)),
                ('patient', models.CharField(max_length=40)),
                ('error_desc', models.CharField(max_length=200)),
                ('free_text', models.CharField(max_length=200)),
                ('day', models.CharField(choices=[('MONDAY', 'Maandag'), ('TUESDAY', 'Dinsdag'), ('WEDNESDAY', 'Woensdag'), ('THURSDAY', 'Donderdag'), ('FRIDAY', 'Vrijdag'), ('SATURDAY', 'Zaterdag'), ('SUNDAY', 'Zondag')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('corrected_by', models.CharField(max_length=40)),
                ('checked_by', models.CharField(max_length=40)),
                ('bag_NR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.bag')),
            ],
        ),
        migrations.CreateModel(
            name='BatchRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=40)),
                ('split_NR', models.IntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('NR_patients', models.IntegerField()),
                ('NR_bags', models.IntegerField()),
                ('MC_CD', models.CharField(choices=[('MC', 'MC'), ('CD', 'CD')], max_length=2)),
                ('remarks', models.CharField(max_length=200)),
                ('batch_NR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.batch')),
            ],
        ),
        migrations.CreateModel(
            name='BatchChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PSS_check_by', models.CharField(max_length=40)),
                ('PSS_check_remarks', models.CharField(max_length=200)),
                ('tray_fill_by', models.CharField(max_length=40)),
                ('tray_check_by', models.CharField(max_length=40)),
                ('tray_fill_check_remarks', models.CharField(max_length=200)),
                ('schouw_by', models.CharField(max_length=40)),
                ('schouw_remarks', models.CharField(max_length=200)),
                ('batch_validation', models.BooleanField()),
                ('batch_validation_by', models.CharField(max_length=40)),
                ('cargo_office_by', models.CharField(max_length=40)),
                ('packaging_by', models.CharField(max_length=40)),
                ('control_seal_by', models.CharField(max_length=40)),
                ('end_check_by', models.CharField(max_length=40)),
                ('internal_error', models.BooleanField()),
                ('empty_bags_delivered', models.BooleanField()),
                ('other_errors', models.BooleanField()),
                ('batch_nr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.batch')),
            ],
        ),
        migrations.AddField(
            model_name='bag',
            name='roll_NR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.roll'),
        ),
    ]
