# Generated by Django 3.1.3 on 2021-01-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_NR', models.CharField(max_length=30)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('total_NR_bags', models.IntegerField()),
                ('bags_checked', models.IntegerField()),
                ('bags_rejected', models.IntegerField()),
                ('NR_to_double_check', models.IntegerField()),
                ('double_checked', models.IntegerField()),
                ('inspector', models.CharField(max_length=40)),
                ('checked_by', models.CharField(max_length=40)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BatchPackagingProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_ID', models.CharField(max_length=10)),
                ('run_day', models.CharField(choices=[('MONDAY', 'Maandag'), ('TUESDAY', 'Dinsdag'), ('WEDNESDAY', 'Woensdag'), ('THURSDAY', 'Donderdag'), ('FRIDAY', 'Vrijdag'), ('SATURDAY', 'Zaterdag'), ('SUNDAY', 'Zondag')], max_length=10)),
                ('week', models.IntegerField()),
                ('line_clearance_by', models.CharField(max_length=40)),
                ('line_clearance_remarks', models.CharField(max_length=200)),
                ('start_check_by', models.CharField(max_length=40)),
                ('start_check_remarks', models.CharField(max_length=200)),
                ('label_check_by', models.CharField(max_length=40)),
                ('label_check_remarks', models.CharField(max_length=200)),
                ('PSS_check_by', models.CharField(max_length=40)),
                ('PSS_check_remarks', models.CharField(max_length=200)),
                ('tray_fill_by', models.CharField(max_length=40)),
                ('tray_check_by', models.CharField(max_length=40)),
                ('tray_fill_check_remarks', models.CharField(max_length=200)),
                ('schouw_by', models.CharField(max_length=40)),
                ('schouw_remarks', models.CharField(max_length=200)),
                ('batch_validation', models.BooleanField()),
                ('batch_validation_by', models.CharField(max_length=40)),
                ('cargo_office_by', models.CharField(max_length=40)),
                ('packaging_by', models.CharField(max_length=40)),
                ('control_seal_by', models.CharField(max_length=40)),
                ('end_check_by', models.CharField(max_length=40)),
                ('leave_day', models.CharField(choices=[('MONDAY', 'Maandag'), ('TUESDAY', 'Dinsdag'), ('WEDNESDAY', 'Woensdag'), ('THURSDAY', 'Donderdag'), ('FRIDAY', 'Vrijdag'), ('SATURDAY', 'Zaterdag'), ('SUNDAY', 'Zondag')], max_length=10)),
                ('leave_time', models.TimeField()),
                ('forward_day', models.CharField(choices=[('MONDAY', 'Maandag'), ('TUESDAY', 'Dinsdag'), ('WEDNESDAY', 'Woensdag'), ('THURSDAY', 'Donderdag'), ('FRIDAY', 'Vrijdag'), ('SATURDAY', 'Zaterdag'), ('SUNDAY', 'Zondag')], max_length=10)),
                ('forward_time', models.IntegerField()),
                ('Slick_start_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_NR', models.IntegerField()),
                ('error', models.CharField(choices=[('TOO_MUCH', 'Te veel'), ('TOO_LITTLE', 'Te weinig'), ('TOO_EARLY', 'Te vroeg'), ('TOO_LATE', 'Te laat')], max_length=10)),
                ('error_desc', models.CharField(max_length=100)),
                ('free_text', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('MONDAY', 'Maandag'), ('TUESDAY', 'Dinsdag'), ('WEDNESDAY', 'Woensdag'), ('THURSDAY', 'Donderdag'), ('FRIDAY', 'Vrijdag'), ('SATURDAY', 'Zaterdag'), ('SUNDAY', 'Zondag')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('corrected_by', models.CharField(max_length=40)),
                ('checked_by', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_NR', models.IntegerField()),
                ('Institute', models.CharField(max_length=40)),
                ('Department', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_NR', models.IntegerField()),
                ('patient', models.CharField(max_length=40)),
                ('packaging_code', models.CharField(max_length=40)),
                ('batch_NR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.batch')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_NR', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='API.batch')),
                ('order_NR', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='API.order')),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_NR', models.IntegerField()),
                ('bag_type', models.CharField(choices=[('PREBAG', 'Voorloopzakje'), ('MEDICATIONBAG', 'Medicatiezakje'), ('AFTERBAG', 'Naloopzakje')], max_length=15)),
                ('roll_NR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.roll')),
            ],
        ),
    ]
