# Generated by Django 3.1.3 on 2020-12-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('roll_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=40)),
                ('medication_packager', models.IntegerField()),
                ('tray_filler', models.IntegerField()),
                ('tray_checker', models.IntegerField()),
                ('tray_checker_comment', models.CharField(max_length=1000)),
                ('photon_operator', models.IntegerField()),
                ('photo_checker', models.IntegerField()),
                ('disapproved_photos', models.CharField(max_length=500)),
                ('corrections_employee', models.IntegerField()),
                ('executed_corrections', models.CharField(max_length=1000)),
                ('corrections_checker', models.IntegerField()),
                ('checked_in_GIS', models.BooleanField()),
                ('final_packager', models.IntegerField()),
                ('final_packaging_description', models.CharField(max_length=500)),
                ('final_checker', models.IntegerField()),
                ('released', models.BooleanField()),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.company')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='API.person')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='API.person'),
        ),
        migrations.AddField(
            model_name='batch',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.order'),
        ),
    ]
