# Generated by Django 3.1.3 on 2020-11-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='customer_id',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='placed_by',
            new_name='person_id',
        ),
    ]
