# Generated by Django 3.1.3 on 2020-11-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201122_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrow',
            name='medication_packager',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
