version: "3.9"
   
services:
  backend:
    build:
      context: backendAPI
      dockerfile: Dockerfile
    command: python manage.py migrate
    command: python manage.py runserver
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
      
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'