version: "3.9"
   
services:
  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'db'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
       