export const batches = [
    {
        batchId: '24-03',
        controle1: true,
        controle1Desc: '',
        controle2: true,
        controle2Desc: '',
        controle3: false,
        controle3Desc: 'Er is iets aangepast',
    },
    {
        batchId: '24-04',
        controle1: true,
        controle1Desc: '',
        controle2: true,
        controle2Desc: 'Er is iets aangepast',
        controle3: false,
        controle3Desc: '',
    },
    {
        batchId: '24-05',
        controle1: true,
        controle1Desc: 'Er is iets aangepast',
        controle2: true,
        controle2Desc: '',
        controle3: false,
        controle3Desc: '',
    },
    {
        batchId: '24-06',
        controle1: true,
        controle1Desc: 'Er is iets aangepast',
        controle2: true,
        controle2Desc: '',
        controle3: false,
        controle3Desc: '',
    },
    {
        batchId: '24-07',
        controle1: true,
        controle1Desc: '',
        controle2: true,
        controle2Desc: 'Er is iets aangepast',
        controle3: false,
        controle3Desc: '',
    },
    {
        batchId: '24-08',
        controle1: true,
        controle1Desc: '',
        controle2: true,
        controle2Desc: '',
        controle3: false,
        controle3Desc: 'Er is iets aangepast',
    }
  ];