export const orders = [
    {
        orderId: '24',
        controle1: true,
        controle1Desc: '',
        controle2: true,
        controle2Desc: '',
        controle3: false,
        controle3Desc: 'Er is iets aangepast',
    },
    {
        orderId: '25',
        controle1: true,
        controle1Desc: '',
        controle2: false,
        controle2Desc: 'Er is iets aangepast',
        controle3: true,
        controle3Desc: '',
    },
    {
        orderId: '26',
        controle1: false,
        controle1Desc: 'Er is iets aangepast',
        controle2: true,
        controle2Desc: '',
        controle3: true,
        controle3Desc: '',
    },
    {
        orderId: '27',
        controle1: false,
        controle1Desc: 'Er is iets aangepast',
        controle2: true,
        controle2Desc: '',
        controle3: true,
        controle3Desc: '',
    },
    {
        orderId: '28',
        controle1: true,
        controle1Desc: '',
        controle2: false,
        controle2Desc: 'Er is iets aangepast',
        controle3: true,
        controle3Desc: '',
    },
    {
        orderId: '29',
        controle1: true,
        controle1Desc: '',
        controle2: true,
        controle2Desc: '',
        controle3: false,
        controle3Desc: 'Er is iets aangepast',
    }
  ];