export const rols = [
    {
        rolId: '24-03-47',
        controle1: true,
        controle1Desc: '',
        controle2: true,
        controle2Desc: '',
        controle3: false,
        controle3Desc: 'Er is iets aangepast',
    },
    {
        rolId: '24-03-48',
        controle1: true,
        controle1Desc: '',
        controle2: false,
        controle2Desc: 'Er is iets aangepast',
        controle3: true,
        controle3Desc: '',
    },
    {
        rolId: '24-03-49',
        controle1: false,
        controle1Desc: 'Er is iets aangepast',
        controle2: true,
        controle2Desc: '',
        controle3: true,
        controle3Desc: '',
    },
    {
        rolId: '24-03-50',
        controle1: false,
        controle1Desc: 'Er is iets aangepast',
        controle2: true,
        controle2Desc: '',
        controle3: true,
        controle3Desc: '',
    },
    {
        rolId: '24-03-51',
        controle1: true,
        controle1Desc: '',
        controle2: false,
        controle2Desc: 'Er is iets aangepast',
        controle3: true,
        controle3Desc: '',
    },
    {
        rolId: '24-03-52',
        controle1: true,
        controle1Desc: '',
        controle2: true,
        controle2Desc: '',
        controle3: false,
        controle3Desc: 'Er is iets aangepast',
    }
  ];